### ISSUE TITLE
Support implicit AND

### ISSUE THREAD

**Issue by gajus** [gajus/liqe#1]
Parser at the moment does not support implicit "AND", i.e. when there is a space between two statements without an operator. In those cases, we want to treat space as "AND".

These tests are marked as skipped:

* [`foo bar`](https://github.com/gajus/liqe/blob/b1efa187d02982ccb7a48c8410779e5a82b24f5c/test/liqe/parse.ts#L18-L30) should be equivalent to `foo AND bar`
* [`foo:bar baz:qux`](https://github.com/gajus/liqe/blob/b1efa187d02982ccb7a48c8410779e5a82b24f5c/test/liqe/parse.ts#L148-L158) should be equivalent to `foo:bar AND baz:qux`

Silving this issue requires editing `src/grammar.ne` to enable the skipped tests.

See https://github.com/gajus/liqe#development for additional details.

**Comment by thecodrr** [comment]
@gajus hopefully this can be added soon. Really looking forward to it.

**Comment by gajus** [comment]
A naive solution is something similar to https://github.com/gajus/liqe/pull/11

The problem with this solution is that it produces ambiguous results
