### ISSUE TITLE
Decide how we handle "foo:"

### ISSUE THREAD

**Issue by gajus** [gajus/liqe#18]
```
foo:
```

On one hand, it is a syntax error since it is missing the expression.

On the other hand, we could provide a lot more user-friendly errors if we identified that the right hand-side is empty.

This would require introducing a new token that represents empty though.

The same "empty" concept could then be applied to an empty query, `()` and other places.

A few outstanding questions, ...

### How do we handle an empty query?

I suppose it would just return an empty token.

```ts
{
  location: {...},
  type: 'EmptyExpression',
}
```

What would the `location` be if though if the query contains multiple whitespaces?

### How do we handle `foo:`?

Same question as with the empty query.

### How do we distinguish `foo: bar`?

At the moment, we allow space between field and expression, i.e. `bar` becomes a value of `foo`.

This change would require that we do not allow space between operator and value. I think that's a good thing either way (https://github.com/gajus/liqe/issues/19).

### How we handle `()` and `(   )`?

The challenge here is that every token has to have `location` with `start,end`.

Let's say that `(   )` has `EmptyExpression`

```ts
{
  location: {start: 1, end: 4},
  type: 'EmptyExpression',
}
```

What would the location be in the earlier example of `foo: bar`?

**Comment by gajus** [comment]
If #20 merges, then things become slightly easier:

### How do we handle an empty query?

Location would always be `{start: 0, end: 0}`, regardless of whitespaces.

### How do we handle foo:?

Location (start and end) would be the end of the comparison operator.

### How do we distinguish `foo: bar`?

* `foo:` becomes an invalid expression with an empty location.
* `bar` is treated as a separate expression without a field.

### How we handle () and ( )?

Location (start and end) would be equal to the open tag.

**Comment by gajus** [comment]
WIP can be seen here https://github.com/gajus/liqe/tree/gajus/introduce-empty

**Comment by MJCD** [comment]
I hate everything about this
