### ISSUE TITLE
Handling strings with period yields error

### ISSUE THREAD

**Issue by cyberwombat** [gajus/liqe#21]
If I just provide a string as a query: `gmail.com` then it breaks because of the period with the error `Found no parsings.`.
```
serialize(parse('gmail.com'))
```

And if I do: `email:foo@gmail.com` then I get another error.  `Syntax error at line 1 column 10`

**Comment by gajus** [comment]
That's expected. Just quote it.

**Comment by gajus** [comment]
Actually, on the second look, there is no reason we cannot support unquoted `.` and `@` characters.

**Comment by cyberwombat** [comment]
I think that not blowing up regardless of whether quoting was required for a valid query is essential. Both sentences yielded different messages - perhaps this could be somehow organized into an invalid query exception that can be captured and passed to user.   I could not tell what issue was from these messages.

**Comment by gajus** [comment]
Technically, it is a syntax error, so it is expected to blow up. The syntax error is what you can use to inform the user of invalid input.

https://github.com/gajus/liqe#handling-syntax-errors

**Comment by gajus** [comment]
I've made some effort with recent changes to avoid "blowing up" unnecessarily, e.g. https://github.com/gajus/liqe/pull/22. But it is a controversial change based on feedback I've received in private. Purist expect parser to break when input is not a valid query.

**Comment by cyberwombat** [comment]
is `Found no parsings.` considered a syntax error?

**Comment by gajus** [comment]
I was referring to:

> And if I do: email:foo@gmail.com then I get another error. Syntax error at line 1 column 10

"Found no parsings." is a different beast altogether. Cannot parse something that we don't have rules to parse.

**Comment by gajus** [comment]
Both `gmail.com` and `email:foo@gmail.com` are now supported.

As you can see from https://github.com/gajus/liqe/commit/5d215e3f6709a2799ea08618e4bc45d61ff2cf38, supporting broader expressions is pretty simple, just need to be careful that we needlessly not introduce unquoted characters that clash with keywords or special syntax (like ranges).

**Comment by gajus** [comment]
e.g. cannot introduce `,` without compromising https://github.com/gajus/liqe/issues/12

**Comment by gajus** [comment]
I think the broadest expression that we can support within ASCII range is:

```
[a-zA-Z_*@#] [a-zA-Z~!@#$%^&*()\-_+=\[\]{};<>.?/]
```

Don't want to rush introducing this as it can easily backfire.
